project:
  type: website
  output-dir: "./docs"

website:
  title: "DISCOV"
  favicon: Data/img/DISCOV_logo.png
  navbar:
    tools:
      - icon: github
        href: https://github.com/SigOiry/DISCOV-MicaSense
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme:      
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
      margin-width: 150px
      sidebar-width: 150px

editor: source


