name: NN_env
channels:
  - fastai
  - conda-forge
dependencies:
  - affine=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.10.3
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - colour=0.1.5
  - comm=0.2.2
  - confection=0.1.4
  - contourpy=1.2.1
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - datasets=2.19.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - dtreeviz=2.2.2
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fastai=2.7.15
  - fastbook=0.0.28
  - fastcore=1.5.33
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - filelock=3.14.0
  - fiona=1.9.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gdal=3.8.4
  - gdk-pixbuf=2.42.11
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=8.4.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - huggingface_hub=0.23.0
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - iniconfig=2.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.10
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langcodes=3.4.0
  - language-data=1.2.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libcxx=17.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libgdal=3.8.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=15.0.0
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.1
  - libre2-11=2023.09.01
  - librsvg=2.58.0
  - librttopo=1.1.0
  - libsentencepiece=0.1.99
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch=2.1.2
  - libutf8proc=2.8.0
  - libuv=1.48.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.5
  - lz4-c=1.9.4
  - lzo=2.10
  - marisa-trie=1.1.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.5
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.10
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nspr=4.35
  - nss=3.98
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=1.9.2
  - packaging=24.0
  - pandas=2.2.2
  - pango=1.52.2
  - parso=0.8.4
  - pathy=0.10.2
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.1
  - pluggy=1.5.0
  - poppler=24.03.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - preshed=3.0.9
  - proj=9.3.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=8.2.0
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-graphviz=0.20.3
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - rasterio=1.3.9
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.4.28
  - requests=2.31.0
  - rich=13.7.1
  - safetensors=0.4.3
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - sentencepiece=0.1.99
  - sentencepiece-python=0.1.99
  - sentencepiece-spm=0.1.99
  - setuptools=69.5.1
  - shapely=2.0.4
  - shellingham=1.5.4
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - snappy=1.1.10
  - snuggs=1.4.7
  - spacy=3.7.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.12.0
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - tiledb=2.20.1
  - tk=8.6.13
  - tokenizers=0.19.1
  - tomli=2.0.1
  - torchvision=0.16.1
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.40.2
  - typer=0.9.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzcode=2024a
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.2.1
  - wasabi=1.1.2
  - wcwidth=0.2.13
  - weasel=0.3.4
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - fastinference==0.0.36
