project:
  type: website
  render: 
    - index.qmd
    - about.qmd
    - DISCOV_Examples.qmd
  output-dir: "../docs"

website:
  title: "DISCOV"
  favicon: ./Imgs/DISCOV_logo.png
  navbar:
    tools:
      - icon: github
        href: https://github.com/SigOiry/DISCOV-MicaSense
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About the model
      - href: DISCOV_Examples.qmd
        text: DISCOV Example
format:
  html:
    include-in-header: 
      text: |
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <meta name="description" content="DISCOV is an intertidal drone classification model developed for Micasense."/>
          <meta name="keywords" content="DISCOV, intertidal mapping, Drone, Classification model, Micasense, Seagrass"/>
          <meta name="author" content="Simon Oiry">
          <meta itemprop="name" content="DISCOV: The Intertidal Drone Classification Model for Micasense"/>
          <meta itemprop="description" content="DISCOV is an intertidal drone classification model developed for Micasense."/>
          <meta itemprop="keywords" content="DISCOV, intertidal mapping, Drone, Classification model, Micasense, Seagrass"/>
        </head>
    theme:      
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
      margin-width: 150px
      sidebar-width: 150px
      gutter-width: 0px

editor: source